<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <LangVersion>12</LangVersion>
    <EmitCompilerGeneratedFiles>true</EmitCompilerGeneratedFiles>
    <OutputItemType>Analyzer</OutputItemType>
    <IncludeBuildOutput>false</IncludeBuildOutput>
    <CompilerGeneratedFilesOutputPath>Generated</CompilerGeneratedFilesOutputPath>
  </PropertyGroup>
  
  <PropertyGroup>
    <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
    <Authors>Martin Drozdík</Authors>
    <Description>A library of generators to support testing of websites using the MartinDrozdik.DDD packages.</Description>
    <PackageProjectUrl>https://github.com/drozdik-m/domain-driven-design/tree/main/src/MartinDrozdik.DDD.Testing.Generators</PackageProjectUrl>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <PackageIcon>ddd-test-icon.png</PackageIcon>
    <RepositoryUrl>https://github.com/drozdik-m/domain-driven-design</RepositoryUrl>
    <PackageTags>ddd;generators;testweb;domain;template</PackageTags>
    <Version>0.7.1.1</Version>
    <PackageId>MartinDrozdik.DDD.Testing.Generators</PackageId>
    <PackageRequireLicenseAcceptance>True</PackageRequireLicenseAcceptance>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <Copyright>© Ing. Martin Drozdík. All rights reserved.</Copyright>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.CodeAnalysis.Analyzers" Version="5.6.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp" Version="5.6.0" />
  </ItemGroup>

  <ItemGroup>
    <None Update="ddd-test-icon.png">
      <PackagePath>\</PackagePath>
      <Pack>True</Pack>
    </None>
  </ItemGroup>

</Project>
