<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
  </PropertyGroup>

  <!-- OpenAPI generation settings -->
  <PropertyGroup>
    <OpenApiGenerateDocumentsOptions>--file-name DemoApi</OpenApiGenerateDocumentsOptions>
    <OpenApiDocumentsDirectory>./OpenApi</OpenApiDocumentsDirectory>
  </PropertyGroup>

  <!-- Generate HTTP client from OpenAPI specification after build in Debug configuration -->
  <Target Name="OpenApi" AfterTargets="Build" Condition="$(Configuration)=='Debug'">
    <Exec Command="kiota generate -l CSharp --clean-output --output ../MartinDrozdik.DDD.Demo.Client/Generated --namespace-name MartinDrozdik.DDD.Demo.Client.Generated --class-name DddClient --exclude-backward-compatible --openapi ./OpenApi/DemoApi.json" WorkingDirectory="$(ProjectDir)" />
  </Target>
  <ItemGroup>
    <None Remove="app.db" />
    <None Remove="app.db-shm" />
    <None Remove="app.db-wal" />
    <None Remove="dev.db" />
    <None Remove="dev.db-shm" />
    <None Remove="dev.db-wal" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="10.0.6" />
    <PackageReference Include="Microsoft.Extensions.ApiDescription.Server" Version="10.0.6">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Scalar.AspNetCore" Version="2.14.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\MartinDrozdik.DDD.Web\MartinDrozdik.DDD.Web.csproj" />
  </ItemGroup>

</Project>
