<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="stylecop.json" />
  </ItemGroup>

  <ItemGroup>
    <AdditionalFiles Include="stylecop.json" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="CSharpFunctionalExtensions" Version="3.6.0" />
    <PackageReference Include="FluentValidation" Version="12.0.0" />
    <PackageReference Include="SonarAnalyzer.CSharp" Version="10.10.0.116381">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="StyleCop.Analyzers" Version="1.1.118">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Enumerations\Errors\EnumerationErrorsResource.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>EnumerationErrorsResource.resx</DependentUpon>
    </Compile>
    <Compile Update="Errors\WellKnown\WellKnownErrorsResource.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>WellKnownErrorsResource.resx</DependentUpon>
    </Compile>
    <Compile Update="Templates\Errors\TemplateErrorsResource.Designer.cs">
      <DependentUpon>TemplateErrorsResource.resx</DependentUpon>
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Enumerations\Errors\EnumerationErrorsResource.cs.resx">
      <LastGenOutput>EnumerationErrorsResource.cs.Designer.cs</LastGenOutput>
      <Generator>ResXFileCodeGenerator</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Enumerations\Errors\EnumerationErrorsResource.resx">
      <LastGenOutput>EnumerationErrorsResource.Designer.cs</LastGenOutput>
      <Generator>ResXFileCodeGenerator</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Errors\WellKnown\WellKnownErrorsResource.cs.resx">
      <LastGenOutput>WellKnownErrorsResource.cs.Designer.cs</LastGenOutput>
      <Generator>ResXFileCodeGenerator</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Errors\WellKnown\WellKnownErrorsResource.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>WellKnownErrorsResource.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="Templates\Errors\TemplateErrorsResource.cs.resx">
      <LastGenOutput>WellKnownErrorsResource.cs.Designer.cs</LastGenOutput>
      <Generator>ResXFileCodeGenerator</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Templates\Errors\TemplateErrorsResource.resx">
      <LastGenOutput>TemplateErrorsResource.Designer.cs</LastGenOutput>
      <Generator>ResXFileCodeGenerator</Generator>
    </EmbeddedResource>
  </ItemGroup>

  <ItemGroup>
    <AssemblyAttribute Include="System.Runtime.CompilerServices.InternalsVisibleTo">
      <_Parameter1>$(MSBuildProjectName).Tests</_Parameter1>
    </AssemblyAttribute>
  </ItemGroup>

</Project>
